In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("credit-score.csv")
df

ID  Customer_ID  Month           Name  Age        SSN Occupation  \
0        5634         3392      1  Aaron Maashoh   23  821000265  Scientist   
1        5635         3392      2  Aaron Maashoh   23  821000265  Scientist   
2        5636         3392      3  Aaron Maashoh   23  821000265  Scientist   
3        5637         3392      4  Aaron Maashoh   23  821000265  Scientist   
4        5638         3392      5  Aaron Maashoh   23  821000265  Scientist   
...       ...          ...    ...            ...  ...        ...        ...   
99995  155625        37932      4          Nicks   25   78735990   Mechanic   
99996  155626        37932      5          Nicks   25   78735990   Mechanic   
99997  155627        37932      6          Nicks   25   78735990   Mechanic   
99998  155628        37932      7          Nicks   25   78735990   Mechanic   
99999  155629        37932      8          Nicks   25   78735990   Mechanic   

       Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  ...  \
0           19114.12            1824.843333                  3  ...   
1           19114.12            1824.843333                  3  ...   
2           19114.12            1824.843333                  3  ...   
3           19114.12            1824.843333                  3  ...   
4           19114.12            1824.843333                  3  ...   
...              ...                    ...                ...  ...   
99995       39628.99            3359.415833                  4  ...   
99996       39628.99            3359.415833                  4  ...   
99997       39628.99            3359.415833                  4  ...   
99998       39628.99            3359.415833                  4  ...   
99999       39628.99            3359.415833                  4  ...   

       Credit_Mix  Outstanding_Debt  Credit_Utilization_Ratio  \
0            Good            809.98                 26.822620   
1            Good            809.98                 31.944960   
2            Good            809.98                 28.609352   
3            Good            809.98                 31.377862   
4            Good            809.98                 24.797347   
...           ...               ...                       ...   
99995        Good            502.38                 34.663572   
99996        Good            502.38                 40.565631   
99997        Good            502.38                 41.255522   
99998        Good            502.38                 33.638208   
99999        Good            502.38                 34.192463   

      Credit_History_Age  Payment_of_Min_Amount  Total_EMI_per_month  \
0                    265                     No            49.574949   
1                    266                     No            49.574949   
2                    267                     No            49.574949   
3                    268                     No            49.574949   
4                    269                     No            49.574949   
...                  ...                    ...                  ...   
99995                378                     No            35.104023   
99996                379                     No            35.104023   
99997                380                     No            35.104023   
99998                381                     No            35.104023   
99999                382                     No            35.104023   

       Amount_invested_monthly                 Payment_Behaviour  \
0                    21.465380   High_spent_Small_value_payments   
1                    21.465380    Low_spent_Large_value_payments   
2                    21.465380   Low_spent_Medium_value_payments   
3                    21.465380    Low_spent_Small_value_payments   
4                    21.465380  High_spent_Medium_value_payments   
...                        ...                               ...   
99995                24.028477   High_spent_Large_value_payments   
99996              

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   ID                        100000 non-null  int64  
 1   Customer_ID               100000 non-null  int64  
 2   Month                     100000 non-null  int64  
 3   Name                      100000 non-null  object 
 4   Age                       100000 non-null  int64  
 5   SSN                       100000 non-null  int64  
 6   Occupation                100000 non-null  object 
 7   Annual_Income             100000 non-null  float64
 8   Monthly_Inhand_Salary     100000 non-null  float64
 9   Num_Bank_Accounts         100000 non-null  int64  
 10  Num_Credit_Card           100000 non-null  int64  
 11  Interest_Rate             100000 non-null  int64  
 12  Num_of_Loan               100000 non-null  int64  
 13  Type_of_Loan              100000 non-null  ob

In [4]:
#encoding, convert to numierical data

df.columns

Index(['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation',
       'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts',
       'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan',
       'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt',
       'Credit_Utilization_Ratio', 'Credit_History_Age',
       'Payment_of_Min_Amount', 'Total_EMI_per_month',
       'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance',
       'Credit_Score'],
      dtype='object')

In [5]:
from sklearn.preprocessing import LabelEncoder

columns = ['Name', 'Occupation', 'Type_of_Loan', 'Credit_Mix', 'Payment_of_Min_Amount',
       'Payment_Behaviour', 'Credit_Score']

for col in columns : 
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

In [6]:
df

ID  Customer_ID  Month  Name  Age        SSN  Occupation  \
0        5634         3392      1    11   23  821000265          12   
1        5635         3392      2    11   23  821000265          12   
2        5636         3392      3    11   23  821000265          12   
3        5637         3392      4    11   23  821000265          12   
4        5638         3392      5    11   23  821000265          12   
...       ...          ...    ...   ...  ...        ...         ...   
99995  155625        37932      4  6508   25   78735990           9   
99996  155626        37932      5  6508   25   78735990           9   
99997  155627        37932      6  6508   25   78735990           9   
99998  155628        37932      7  6508   25   78735990           9   
99999  155629        37932      8  6508   25   78735990           9   

       Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  ...  \
0           19114.12            1824.843333                  3  ...   
1           19114.12            1824.843333                  3  ...   
2           19114.12            1824.843333                  3  ...   
3           19114.12            1824.843333                  3  ...   
4           19114.12            1824.843333                  3  ...   
...              ...                    ...                ...  ...   
99995       39628.99            3359.415833                  4  ...   
99996       39628.99            3359.415833                  4  ...   
99997       39628.99            3359.415833                  4  ...   
99998       39628.99            3359.415833                  4  ...   
99999       39628.99            3359.415833                  4  ...   

       Credit_Mix  Outstanding_Debt  Credit_Utilization_Ratio  \
0               1            809.98                 26.822620   
1               1            809.98                 31.944960   
2               1            809.98                 28.609352   
3               1            809.98                 31.377862   
4               1            809.98                 24.797347   
...           ...               ...                       ...   
99995           1            502.38                 34.663572   
99996           1            502.38                 40.565631   
99997           1            502.38                 41.255522   
99998           1            502.38                 33.638208   
99999           1            502.38                 34.192463   

       Credit_History_Age  Payment_of_Min_Amount  Total_EMI_per_month  \
0                     265                      1            49.574949   
1                     266                      1            49.574949   
2                     267                      1            49.574949   
3                     268                      1            49.574949   
4                     269                      1            49.574949   
...                   ...                    ...                  ...   
99995                 378                      1            35.104023   
99996                 379                      1            35.104023   
99997                 380                      1            35.104023   
99998                 381                      1            35.104023   
99999                 382                      1            35.104023   

       Amount_invested_monthly  Payment_Behaviour  Monthly_Balance  \
0                    21.465380                  2       312.494089   
1                    21.465380                  3       284.629163   
2                    21.465380                  4       331.209863   
3                    21.465380                  5       223.451310   
4                    21.465380                  1       341.489231   
...                        ...                ...              ...   
99995                24.028477                  0       479.866228   
99996                24.028477                  1       496.651610   
99997            

In [7]:
#separate data target

x = df.drop('Credit_Score', axis = 1)
y = df['Credit_Score']

In [8]:
#split data

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

In [9]:
#panggil model KNN

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
model.fit(x_train, y_train)

KNeighborsClassifier()

In [10]:
predicted = model.predict(x_test) #var predicted bakal nampung data hasilnya

In [11]:
#Evalusai Model
#ConfusionMatrix berfungsi menghitung jumlah data yang error dan berhasil dari data test dan aktual

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(y_test, predicted))

#benar 9573, 339
#salah 986, 405. Semakin kecil error maka semakin bagus model ML nya

[[ 3413    35   980]
 [   70  5956  1251]
 [ 1228  1716 10351]]


In [12]:
print(classification_report(y_test, predicted))

              precision    recall  f1-score   support

           0       0.72      0.77      0.75      4428
           1       0.77      0.82      0.79      7277
           2       0.82      0.78      0.80     13295

    accuracy                           0.79     25000
   macro avg       0.77      0.79      0.78     25000
weighted avg       0.79      0.79      0.79     25000



In [14]:
print(accuracy_score(predicted, y_test))

0.7888
